# This actions validates the gradle files and runs a build test to ensure the app is not corrupted
name: Validate gradle build test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Change wrapper permissions
        # for some reason the gradle-build-action doesn't do this automatically
        run: chmod +x ./gradlew

      - name: Build & test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: >
            build
            test
