# A Github Action to statically validate Fastlane metadata for Android (supply) using a simple validation logic written in Golang.
# https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata
# https://github.com/marketplace/actions/validate-fastlane-supply-metadata
name: Validate Fastlane Supply Metadata

on:
  # run this workflow on master branch push
  push:
    branches:
      - master
      - 2025-fastlane-migration
  # run this workflow on master pull requests
  pull_request:

# Cancel running actions if new commits are added
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/checkout@v5

      - name: Validate Fastlane files
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
            usePlayStoreLocales: true # optional